apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browser-app
  template:
    metadata:
      labels:
        app: browser-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: static-content
        configMap:
          name: browser-app-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: browser-app-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Hello from GitOps</title></head>
    <body><h1>Hello from Argo CD + Minikube!</h1></body>
    </html>